version: "3.9"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:9696/prowlarr/ping"]
      interval: 5s
      retries: 10

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DOWNLOAD_ROOT}:/downloads
      - "${MEDIA_ROOT}/TV Shows:/tv"
    ports:
      - 8989:8989
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping"]
      interval: 5s
      retries: 10

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DOWNLOAD_ROOT}:/downloads
      - ${MEDIA_ROOT}/Movies:/movies
    ports:
      - 7878:7878
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:7878/radarr/ping"]
      interval: 5s
      retries: 10

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/overseer:/config
    ports:
      - 5055:5055
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:5055/radarr/ping"]
      interval: 5s
      retries: 10

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DOWNLOAD_ROOT}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "http://127.0.0.1:8080/api/v2/app/version"]
      interval: 5s
      retries: 10

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy
    ports:
      - 80:80
      - 81:81
      - 443:443
    restart: always
    environment:
      DB_MYSQL_HOST: "proxy-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "npm"
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "EvwE924yc82rvpDfBzpv"
    volumes:
      - ${CONFIG_ROOT}/proxy/data:/data
      - ${CONFIG_ROOT}/proxy/letsencrypt:/etc/letsencrypt

  proxy-db:
    image: jc21/mariadb-aria:latest
    container_name: proxy-db
    restart: always
    environment:
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "EvwE924yc82rvpDfBzpv"
      MYSQL_ROOT_PASSWORD: "EvwE924yc82rvpDfBzpv"
    volumes:
      - ${CONFIG_ROOT}/proxy/db:/var/lib/mysql

networks:
  default:
    name: media-server-network
